name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-jvm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Deploy with Maven
        run: mvn clean deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: nebula.zip
          path: nebula-cli/target/nebula.zip

  determine-version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get-version.outputs.VERSION }}  # Pass the version as output
    steps:
      - name: Determine version
        id: get-version
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
              echo "VERSION=next" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

  build-docker:
    needs:
      - determine-version
      - build-jvm
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: nebula.zip
          path: nebula-cli/target/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        working-directory: nebula-cli
        run: |
          docker buildx create --use --name multiarch-builder
          docker buildx inspect multiarch-builder --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t orbitalhq/nebula:${{ needs.determine-version.outputs.VERSION }} --push .

